# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  armDeploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Deploy RG rg-githubaction with Azure CLI
#        uses: Azure/cli@v1.0.9
#        with:
#          inlinescript: |
#            az deployment sub create --location "Australia East" --template-file ./arm-templates/resourcegroup.json

      - name: Deploy RG rg-githubaction with (ARM) Template
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: subscription
          subscriptionId: b4b11c34-7f53-4715-ad3e-9129f34cc874
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubaction

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubaction
          subscriptionId: b4b11c34-7f53-4715-ad3e-9129f34cc874
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentName: incremental
            
            